name: Terraform Apply All

on:
  workflow_dispatch:

jobs:
  apply-all:
    name: Apply All Terraform Modules
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Orchestration Repo
        uses: actions/checkout@v3

      - name: Checkout network-terraform
        uses: actions/checkout@v3
        with:
          repository: eamaral/network-terraform
          path: network-terraform
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Checkout alb-terraform
        uses: actions/checkout@v3
        with:
          repository: eamaral/alb-terraform
          path: alb-terraform
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Checkout cognito-terraform
        uses: actions/checkout@v3
        with:
          repository: eamaral/cognito-terraform
          path: cognito-terraform
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Checkout ecs-terraform
        uses: actions/checkout@v3
        with:
          repository: eamaral/ecs-terraform
          path: ecs-terraform
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Checkout db-terraform
        uses: actions/checkout@v3
        with:
          repository: eamaral/db-terraform
          path: db-terraform
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Checkout api-gateway-terraform
        uses: actions/checkout@v3
        with:
          repository: eamaral/api-gateway-terraform
          path: api-gateway-terraform
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Terraform Apply - network
        working-directory: network-terraform
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Terraform Apply - alb
        working-directory: alb-terraform
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Terraform Apply - cognito
        working-directory: cognito-terraform
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Terraform Apply - ecs
        working-directory: ecs-terraform
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Terraform Apply - db
        working-directory: db-terraform
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Terraform Apply - api-gateway
        working-directory: api-gateway-terraform
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Dar permissão de execução ao script
        run: chmod +x generate-env.sh

      - name: Gerar .env.example com outputs do Terraform
        run: ./generate-env.sh

      - name: Commitar .env.example no repositório do backend
        run: |
          git clone https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/eamaral/fastfood-backend.git
          cd fastfood-backend
          mv ../.env.example .env.example
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .env.example
          git commit -m "Atualiza .env.example com outputs do Terraform" || echo "Nada para commitar"
          git push origin main
